# Generated by Django 4.2.14 on 2026-03-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="match",
            name="score_away",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="score_home",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[("SCHEDULED", "Запланирован"), ("COMPLETED", "Завершен")],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captained_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("ECON", "Экономический"),
                    ("BUS", "Бизнес"),
                    ("ENG", "Инженерный"),
                    ("IT", "Информационные технологии"),
                    ("LAW", "Юридический"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("BASKETBALL", "Баскетбол"),
                            ("FOOTBALL", "Футбол"),
                            ("VOLLEYBALL", "Волейбол"),
                            ("FUTSAL", "Мини-футбол"),
                        ],
                        max_length=20,
                    ),
                ),
                ("season", models.CharField(default="2025/2026", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Планирование"),
                            ("ACTIVE", "Активна"),
                            ("FINISHED", "Завершена"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_leagues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-season", "sport"],
            },
        ),
    ]
