# Generated by Django 4.2.14 on 2026-04-07 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leagues", "0009_alter_match_status_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="возраст"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="course",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 курс"),
                    ("2", "2 курс"),
                    ("3", "3 курс"),
                    ("4", "4 курс"),
                    ("5", "5 курс"),
                    ("6", "6 курс"),
                ],
                default="",
                max_length=2,
                verbose_name="курс",
            ),
        ),
        migrations.CreateModel(
            name="CoachRosterAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ADD", "Добавлен"), ("REMOVE", "Удален")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_action_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_actions",
                        to="leagues.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
