# Generated by Django 4.2.14 on 2026-04-07 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leagues", "0010_userprofile_age_userprofile_course_coachrosteraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="course",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 курс"),
                    ("2", "2 курс"),
                    ("3", "3 курс"),
                    ("4", "4 курс"),
                    ("5", "5 курс"),
                    ("6", "6 курс"),
                ],
                default="",
                max_length=2,
                verbose_name="курс",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="reserve_players",
            field=models.ManyToManyField(
                blank=True,
                related_name="reserve_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="запас",
            ),
        ),
    ]
