# Generated by Django 4.2.14 on 2026-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0011_team_course_team_reserve_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, default="", verbose_name="описание"),
        ),
    ]
